local constants = {}

local core = require("Core")

constants.someHeight = Vector(0, 0.3, 0)

--[[
buttonPassAnchors -> pass_turn_anchors
forceToken -> marker_combat
intrigue_pos -> constants.intrigue_base
imperium_pos -> constants.imperium_deck
pos_starter_decks = -> constants.players.Red.drawDeck
]]--

constants.turnOrder = {
    Green = 'Yellow',
    Yellow = 'Blue',
    Blue = 'Red',
    Red = 'Green',
}

-- Don't store object references for these objects which can be reloaded / mutated on locale change.
constants.books = {
    base = "6ec3b0",
    faq = "86033d",
    riseOfIx = "57bf60",
    immortality = "537207",
    blitz = nil
}

-- Don't store object references for these objects which can be reloaded / mutated on locale change.
constants.leaders = {
    yuna = "0b6322",
    hundro = "6e3714",
    memnon = "d9daed",
    ariana = "4d862a",
    ilesa = "158da6",
    armand = "796f0a",
    paul = "2df658",
    leto = "9b6cdc",
    tessia = "1839fa",
    rhombur = "691ca6",
    rabban = "4cf050",
    vladimir = "98cae8",
    ilban = "78551e",
    helena = "5a8a9a"
}

--[[
    Temporary structure (set to nil *after* loading). On loading, two mirrors of
    this structure are created with the GUIDs resolved:
    - constants.players
    - constants.alivePlayers
]]--
constants.unresolvedPlayers = {
    Red = {
        board = "adcd28",
        spice = "3074d4",
        solari = "576ccd",
        water = "692c4d",
        leader_zone = "66cdbb",
        dreadnoughts = {"1a3c82", "a8f306"},
        dreadnought_positions = {
            core.getHardcodedPositionFromGUID('1a3c82', -26.2999954, 1.11258292, 18.6999836),
            core.getHardcodedPositionFromGUID('a8f306', -28.6999989, 1.112583, 18.6999817)
        },
        agents = {"7751c8", "afa978"},
        agent_positions = {
            core.getHardcodedPositionFromGUID('7751c8', -17.0, 1.11060059, 20.3),
            core.getHardcodedPositionFromGUID('afa978', -18.3, 1.11060059, 20.3)
        },
        swordmaster = "ed3490",
        council_token = "f19a48",
        council_zone = core.getHardcodedPositionFromGUID('074f6d', -0.0310453977, 0.588213563, 5.520437) + Vector(-1.54, 1, 0),
        council_bonus_zone = core.getHardcodedPositionFromGUID('f19a48', -27.5, 1.23473155, 20.0) + Vector(0, 0.05, 0),
        vanilla_council_zone = core.getHardcodedPositionFromGUID('074f6d', -0.0310453977, 0.588213563, 5.520437) + Vector(-1.73, 1, 0),
        vp_4_players_token = "a6c2e0",
        vp_4_players_token_initial_position = core.getHardcodedPositionFromGUID('a6c2e0', -13.0, 1.31223142, 21.85),
        score_marker = "4feaca",
        flag_bag = '61453d',
        troops = {
            "fd5673",
            "81763a",
            "6c2b85",
            "8b2acc",
            "8bb1e6",
            "26904f",
            "d1787e",
            "af7cd0",
            "1bbf1c",
            "1fb4ed",
            "0fa955",
            "465c38"
        },
        marker_combat = '2d1d17',
        discardPosition = core.getHardcodedPositionFromGUID('e07493', -14.0, 1.79567933, 16.5) + constants.someHeight,
        drawDeck = "b8e747",
        drawDeckZone = "4f08fc",
        discardZone = "e07493",
        trash = "ea3fe1",
        techZone = '9555b8',
        pass_turn_anchors = "0e9fa2",
        tleilaxuTokens = "2bfc39",
        tleilaxuTokens_inital_position = core.getHardcodedPositionFromGUID('2bfc39', 0.3761088, 0.87810266, 20.6450424),
        researchTokens = "39e0f3",
        researchTokens_inital_position = core.getHardcodedPositionFromGUID('39e0f3', 0.173057809, 0.8806028, 16.8245316),
        cargo = "e9096d",
        zone_player = "2b7781",
        leaderPos = core.getHardcodedPositionFromGUID('66cdbb', -19.0, 1.25, 17.5),
        first_player_positions = core.getHardcodedPositionFromGUID('346e0d', -14.0, 1.5, 19.7) + Vector(0, -0.4, 0)
    },
    Blue = {
        board = "77ca63",
        spice = "9cc286",
        solari = "fa5236",
        water = "0afaeb",
        leader_zone = "681774",
        dreadnoughts = {"82789e", "60f208"},
        dreadnought_positions = {
            core.getHardcodedPositionFromGUID('82789e', -26.2999973, 1.11258316, -4.300006),
            core.getHardcodedPositionFromGUID('60f208', -28.6999969, 1.11258316, -4.300022)
        },
        agents = {"64d013", "106d8b"},
        agent_positions = {
            core.getHardcodedPositionFromGUID('64d013', -17.0, 1.11060047, -2.7),
            core.getHardcodedPositionFromGUID('106d8b', -18.3, 1.11060047, -2.7)
        },
        swordmaster = "a78ad7",
        council_token = "f5b14a",
        council_zone = core.getHardcodedPositionFromGUID('074f6d', -0.0310453977, 0.588213563, 5.520437) + Vector(-0.81, 1, 0),
        council_bonus_zone = core.getHardcodedPositionFromGUID('f5b14a', -27.5, 1.23473155, -3.0) + Vector(0, 0.05, 0),
        vanilla_council_zone = core.getHardcodedPositionFromGUID('074f6d', -0.0310453977, 0.588213563, 5.520437) + Vector(-1.00, 1, 0),
        vp_4_players_token = "311255",
        vp_4_players_token_initial_position = core.getHardcodedPositionFromGUID('311255', -13.0, 1.11223137, -1.14999962),
        score_marker = "1b1e76",
        flag_bag = '8627e0',
        troops = {
            "bc6e74",
            "5fba3c",
            "f2c21f",
            "2a5276",
            "f60d9c",
            "949f2d",
            "0e57c9",
            "694553",
            "f65e5d",
            "c64616",
            "46c1c6",
            "49afee"
        },
        marker_combat = 'f22e20',
        discardPosition = core.getHardcodedPositionFromGUID('26bf8b', -14.0, 1.86566067, -6.5) + constants.someHeight,
        drawDeck = "a76b37",
        drawDeckZone = "907f66",
        discardZone = "26bf8b",
        trash = "52a539",
        techZone = '2d3346',
        pass_turn_anchors = "643f32",
        tleilaxuTokens = "96607f",
        tleilaxuTokens_inital_position = core.getHardcodedPositionFromGUID('96607f', 0.358834058, 0.8806026, 21.36463),
        researchTokens = "292658",
        researchTokens_inital_position = core.getHardcodedPositionFromGUID('292658', 0.19322297, 0.8781026, 17.5218124),
        cargo = "68e424",
        zone_player = "621cc4",
        leaderPos = core.getHardcodedPositionFromGUID('681774', -19.0, 1.25506675, -5.5),
        first_player_positions = core.getHardcodedPositionFromGUID('1fc559', -14.0, 1.501278, -3.3) + Vector(0, -0.4, 0)
    },
    Green = {
        board = "0bbae1",
        spice = "22478f",
        solari = "e597dc",
        water = "fa9522",
        leader_zone = "cf1486",
        dreadnoughts = {"a15087", "734250"},
        dreadnought_positions = {
            core.getHardcodedPositionFromGUID('a15087', 26.3000011, 1.11258316, 18.6999855),
            core.getHardcodedPositionFromGUID('734250', 28.7000046, 1.11258292, 18.6999683)
        },
        agents = {"66ae45", "bceb0e"},
        agent_positions = {
            core.getHardcodedPositionFromGUID('66ae45', 17.0, 1.11060059, 20.3),
            core.getHardcodedPositionFromGUID('bceb0e', 18.3, 1.11060047, 20.3)
        },
        swordmaster = "fb1629",
        council_token = "a0028d",
        council_zone = core.getHardcodedPositionFromGUID('074f6d', -0.0310453977, 0.588213563, 5.520437) + Vector(0.83, 1, 0),
        council_bonus_zone = core.getHardcodedPositionFromGUID('a0028d', 27.5, 1.23473155, 20.0) + Vector(0, 0.05, 0),
        vanilla_council_zone = core.getHardcodedPositionFromGUID('074f6d', -0.0310453977, 0.588213563, 5.520437) + Vector(0.66, 1, 0),
        vp_4_players_token = "66444c",
        vp_4_players_token_initial_position = core.getHardcodedPositionFromGUID('66444c', 13.0, 1.31223142, 21.85),
        score_marker = "76039f",
        flag_bag = 'ad6b92',
        troops = {
            "f433eb",
            "b614cc",
            "60c92d",
            "167fd4",
            "08be0c",
            "a67287",
            "2852e1",
            "fc9c62",
            "b48887",
            "2b1cf8",
            "8e22cc",
            "866a9c"
        },
        marker_combat = 'a1a9a7',
        discardPosition = core.getHardcodedPositionFromGUID('2298aa', 24.0, 1.70515823, 16.5) + constants.someHeight,
        drawDeck = "0c5e03",
        drawDeckZone = "6d8a2e",
        discardZone = "2298aa",
        trash = "4060b5",
        techZone = '546163',
        pass_turn_anchors = "65876d",
        tleilaxuTokens = "63d39f",
        tleilaxuTokens_inital_position = core.getHardcodedPositionFromGUID('63d39f', 1.07565093, 0.880602539, 20.6561527),
        researchTokens = "658b17",
        researchTokens_inital_position = core.getHardcodedPositionFromGUID('658b17', 0.184157625, 0.87810266, 18.91703),
        cargo = "34281d",
        zone_player = "111023",
        leaderPos = core.getHardcodedPositionFromGUID('cf1486', 19.0, 1.18726385, 17.5),
        first_player_positions = core.getHardcodedPositionFromGUID('59523d', 14.0, 1.45146358, 19.7) + Vector(0, -0.4, 0)
    },
    Yellow = {
        board = "fdd5f9",
        spice = "78fb8a",
        solari = "c5c4ef",
        water = "f217d0",
        leader_zone = "a677e0",
        dreadnoughts = {"5469fb", "71a414"},
        dreadnought_positions = {
            core.getHardcodedPositionFromGUID('5469fb', 26.3000011, 1.1125834, -4.29999352),
            core.getHardcodedPositionFromGUID('71a414', 28.7000084, 1.11258316, -4.30001926)
        },
        agents = {"5068c8", "67b476"},
        agent_positions = {
            core.getHardcodedPositionFromGUID('5068c8', 17.0, 1.11060059, -2.7),
            core.getHardcodedPositionFromGUID('67b476', 18.3, 1.11060047, -2.7)
        },
        swordmaster = "635c49",
        council_token = "1be491",
        council_zone = core.getHardcodedPositionFromGUID('074f6d', -0.0310453977, 0.588213563, 5.520437) + Vector(1.60, 1, 0),
        council_bonus_zone = core.getHardcodedPositionFromGUID('1be491', 27.5, 1.23473155, -2.999999) + Vector(0, 0.05, 0),
        vanilla_council_zone = core.getHardcodedPositionFromGUID('074f6d', -0.0310453977, 0.588213563, 5.520437) + Vector(1.37, 1, 0),
        vp_4_players_token = "4e8873",
        vp_4_players_token_initial_position = core.getHardcodedPositionFromGUID('4e8873', 13.0, 1.31223142, -1.14999914),
        score_marker = "20bbd1",
        flag_bag = 'b92a4c',
        troops = {
            "ef6da2",
            "4d0dbf",
            "7c5b7b",
            "fbf8d2",
            "d01e0b",
            "79cbf1",
            "96d089",
            "b5d32e",
            "9b55e4",
            "fd7fc7",
            "ef9008",
            "734b6e"
        },
        marker_combat = 'c2dd31',
        discardPosition = core.getHardcodedPositionFromGUID('6bb3b6', 24.0, 1.66282058, -6.5) + constants.someHeight,
        drawDeck = "014c6a",
        drawDeckZone = "e6cfee",
        discardZone = "6bb3b6",
        trash = "7d1e07",
        techZone = '3d705e',
        pass_turn_anchors = "65876d",
        tleilaxuTokens = "d20bcf",
        tleilaxuTokens_inital_position = core.getHardcodedPositionFromGUID('d20bcf', 1.0899967, 0.880602658, 21.3422337),
        researchTokens = "8988cf",
        researchTokens_inital_position = core.getHardcodedPositionFromGUID('8988cf', 0.189716741, 0.8781027, 18.22235),
        cargo = "8fa76f",
        zone_player = "20859b",
        leaderPos = core.getHardcodedPositionFromGUID('a677e0', 19.0, 1.17902148, -5.5),
        first_player_positions = core.getHardcodedPositionFromGUID('e9a44c', 14.0, 1.44851, -3.3) + Vector(0, -0.4, 0)
    }
}

--[[
    Temporary structure (set to nil *after* loading).
    Note: system / space, not extension, first.
]]--
constants.unresolvedStructure = {
    main = {
        board = "2da390",
        councilZone = "e51f6e",
        makerAndRecall = "120026",
        maker_initial_position = core.getHardcodedPositionFromGUID('fb41e2', -4.08300161, 0.721966565, -12.01027),
        marker_positions = {}
    },
    ix = {
        board = 'd75455'
    },
    immortality = {
        board = "d5c2db",
        specimenZone = "f5de09",
        reclaimed_forces = "3c772c",
        tleilaxu_deck = "dcad54",
        tleilaxuDeckZone = '14b2ca',
        tleilaxuRowSlots = {
            {zone = 'e5ba35', pos = core.getHardcodedPositionFromGUID('439df9', -7.58550072, 0.5361512, 16.0389957) + constants.someHeight},
            {zone = '1e5a32', pos = core.getHardcodedPositionFromGUID('363f98', -5.04514647, 0.513785, 16.0400372) + constants.someHeight}
        },
    },
    intrigue = {
        deck = "77d25d",
        deckZone = "a377d8",
        deckAnchor = "976c3a",
        discardBackCard = "90f762",
        intrigue_immortality = "a5dbab",
        intrigue_ix = "afa5e5",
        intrigue_base = "77d25d"
    },
    imperium = {
        imperiumDeckZone = '8bd982',
        cardsFoldspace = "014161",
        cardsLiaison = "7d34c9",
        cardsTSMF = "8de6d5",
        cardsBaseImperium = "99d41d",
        imperium_deck = "99d41d",
        imperium_deck_ix = "58c4c3",
        imperium_deck_immortality = "88b666",
        imperiumRowSlots = {
            {zone = '3de1d0', pos = core.getHardcodedPositionFromGUID('38ffc0', -7.5, 0.5, 9.0) + constants.someHeight},
            {zone = '356e2c', pos = core.getHardcodedPositionFromGUID('21b287', -5.0, 0.5, 9.0) + constants.someHeight},
            {zone = '7edbb3', pos = core.getHardcodedPositionFromGUID('0a5f50', -2.5, 0.5, 9.0) + constants.someHeight},
            {zone = '641974', pos = core.getHardcodedPositionFromGUID('ded672', 0.0, 0.5, 9.0) + constants.someHeight},
            {zone = 'c6dbed', pos = core.getHardcodedPositionFromGUID('ad2a82', 2.5, 0.5, 9.0) + constants.someHeight}
        },
    },
    starterCards = {
        epic_cards = {'7ae7f5', 'fbaf9f', '497c84', '30b760'},
        starter_decks = {"014c6a", "b8e747", "0c5e03", "a76b37"},
        dune_decks = {"8c99a3", "af840c", "44069d", "85fb54"},
        experimentation_decks = {"ef9531", "45ce21", "2d935f", "8ed0cd"},
    },
    accessories = {
        first_player_marker = "1f5576",
        lowerTrashPosition = core.getHardcodedPositionFromGUID('ef8614', 2.0719285, 0.646084964, -20.6404324) + constants.someHeight,
    }
}

constants.superStructure =
{
    official_characters = {
        board = "7ded4f",
        board_zone = "550f6d",
        hidden_zone = "0e6313",
        ["Leaders Randomizer bag"] = "cf6ca1",
        characters = {
            ["Baron Harkonnen"] = "98cae8",
            ["Helena Richese"] = "5a8a9a",
            ["Earl Memnon"] = "d9daed",
            ["Countess Ariana"] = "4d862a",
            ["Count Ilban"] = "78551e",
            ["Rabban \"The Beast\""] = "4cf050",
            ["Paul Atreides"] = "2df658",
            ["Duke Leto"] = "9b6cdc",
            ["Viscount Hundro"] = "6e3714",
            ["Archduke Armand"] = "796f0a",
            ["Princess Yuna"] = "0b6322",
            ["Ilesa Ecaz"] = "158da6",
            ["Tessia Vernius"] = "1839fa",
            ["Prince Rhombur"] = "691ca6"
        },
        ["Baron Harkonnen Tokens Bag"] = "f89231",
        ["Baron Harkonnen Instruction Card"] = "2b2575",
        ["Tessia Vernius Snooper Tokens"] = {
            "b10897",
            "bed196",
            "a58ce8",
            "857f74"
        },
        hagal_core_deck = "a710bc",
        hagal_imperium_churn_deck = "adbaeb",
        hagal_mentat_5_solari_token = "ba730f",
        hagal_vp = {
            ["Rival's VP (3 Water)"] = "0c4ca1",
            ["Rival's VP (7 Spice)"] = "2fd6f0",
            ["Rival's VP (3 Intrigue)"] = "f9bc89",
            ["Rival's VP (7 Solari)"] = "61c242",
        }
    },
    fanbase_characters = {
        board = "5a682a",
        characters = {
            ["Darwi Odrade"] = "2bf676",
            ["Shaddam IV"] = "2fb2f1",
            ["Miles Teg"] = "7bdba3",
            ["Esmar Tuek"] = "ec4142",
            ["Xavier Harkonnen"] = "83b4e1",
            ["Serena Butler"] = "c34187",
            ["Norma Cenva"] = "80b577",
            ["Princess Irulan"] = "514559",
            ["Princess Wensicia"] = "5d90ae",
            ["Feyd-Rautha"] = "84581f",
            ["Abulurd Harkonnen"] = "4f8d56",
            ["Captain Otto"] = "97564a",
            ["Lady Fenring"] = "a35523",
            ["Count Fenring"] = "bff714",
            ["Earl Memnon"] = "f3082c",
            Executrix = "36f600",
            ["Vorian Atreides"] = "0cffc9",
            ["Whitmore Bludd"] = "c4d7e4",
            Scytale = "14dbb8",
            ["Duke Mutelli"] = "5133d2",
            Farok = "73e664"
        }
    },
    hidden_accessories = {
        board = "6e10cb",
        hidden_zone = "e88cd0",
        dune_the_desert_planet_deck_zones = {
            "e23476",
            "355dc0",
            "d3521b",
            "7b2ba8"
        },
        dune_the_desert_planet_deck = {
            "8c99a3",
            "af840c",
            "44069d",
            "85fb54"
        },
        control_the_spice_card = {
            "497c84",
            "30b760",
            "fbaf9f",
            "7ae7f5"
        },
        ix_intrigue_deck_zone_contribution = "afa5e5",
        ix_imperium_deck_zone_contribution = "58c4c3",
        immortality_intrigue_deck_zone_contribution = "a5dbab",
        immortality_imperium_deck_zone_contribution = "88b666",
        immortality_experimentation_decks = {
            "ef9531",
            "45ce21",
            "2d935f",
            "8ed0cd"
        },
        trash = "433052",
        hagal = {
            hagal_text = "328efa",
            ["Rise of Ix 2P Deck"] = "1f3751",
            ["2P Deck"] = "43a37f",
            ["Rise of Ix 1P Deck"] = "cb48b7",
            ["1P Deck"] = "2d887f",
            ["Everytime except with Immortality 1P Deck"] = "d1ff61",
            ["Immortality 1P Deck"] = "9f6ea8",
            ["Rise of Ix Deck"] = "dd0da1",
            ["Without Rise of Ix Deck"] = "72d430"
        },
        Green = {
            start_end_turn_button = "96aa58"
        },
        Yellow = {
            start_end_turn_button = "3d1b90"
        },
        Blue = {
            start_end_turn_button = "9eeccd"
        },
        Red = {
            start_end_turn_button = "895594"
        }
    },
    top_accessories = {
        Green = {
            swordmaster = "fb1629"
        },
        Yellow = {
            swordmaster = "635c49"
        },
        Blue = {
            swordmaster = "a78ad7"
        },
        Red = {
            swordmaster = "ed3490"
        },
        ["Voice Tokens"] = {
            "cc0eda",
            "516df5"
        },
        ["ix_Tech Tiles Bag"] = "cb766f",
        ["ix_Tech FR Tiles Bag"] = "6116af",
        ["Research Station Patch"] = "54413c",
        vp_area = {
        base_vp = {
            ["The Spice must Flow Bag"] = "43c7b5",
            ["Guild Ambassador Bag"] = "4bdbd5",
            ["Sayyadina Bag"] = "4575f3",
            ["Opulence Bag"] = "67fbba",
            ["The Sleeper must awaken"] = "946ca1",
            ["Staged Incident"] = "bee42f",
            ["Endgame Card Bag"] = "cfe0cb",
            ["Endgame Tech Bag"] = "1d3e4f",
            ["Combat's VP Bag"] = "d9a457"
        },
        ix_vp = {
            ["Detonation Devices Bag"] = "7b3fa2",
            ["Ixian Engineer Bag"] = "3371d8",
            Flagship = "366237",
            ["Spy Satellites"] = "73a68f",
            ["CHOAM Shares"] = "c530e6"
        },
        immortality_vp = {
            ["immortality_Scientific Breakthrough"] = "d22031",
            ["immortality_Bene Tleilax Bag"] = "082e07",
            ["immortality_For Humanity Bag"] = "71c0c8"
        }
        }
    },
    bottom_accessories = {
        ["Base Rules"] = "9ac7d6",
        ["Base Reference Sheet"] = "a4a8a7",
        resolving_ties_in_conflict = "bc4d70",
        ["Rise of Ix Rulebook"] = "373d17",
        ["Immortality Rules"] = "537207",
        blitz_rules = "44e3ba",
        turn_summary_sheet = "e43180",
        ["Randomise Players Positions"] = "9ea771",
        credits_note = "dbc17c",
        trash = "ef8614"
    },
    players = {
        Green = {
        __board = "0c408d",
        character_zone = "cf1486",
        draw_deck = "b8e747",
        draw_deck_zone = "6d8a2e",
        discard_deck_zone = "2298aa",
        first_player_zone = "59523d",
        banner_bag = "ad6b92",
        councilor = "a0028d",
        agents = {
            "66ae45",
            "bceb0e"
        },
        dreadnoughts = {
            "a15087",
            "734250"
        },
        pv_board = "caaba4",
        pv_board_zone = "0e374f",
        troup_zone = "bdfade",
        troup_bowl = "126c3c",
        troups = {
            "f433eb",
            "b614cc",
            "60c92d",
            "167fd4",
            "08be0c",
            "a67287",
            "2852e1",
            "fc9c62",
            "b48887"
        },
        spice_counter = "22478f",
        solari_counter = "e597dc",
        water_counter = "fa9522",
        pass_turn_anchor = "9c69b9",
        __agent_turn_text = "1241fe",
        agent_and_reveal_zone = "890115",
        __tech_board = "96b94b",
        __tech_board_text = "e7c444",
        tech_board_zone = "546163",
        trash = "4060b5",
        hand_trigger = "482f72",
        ["VP 4 Players"] = "66444c",
        ix_atomics = "0a22ec"
        },
        Yellow = {
        board = "6037b3",
        character_zone = "a677e0",
        draw_deck = "a76b37",
        draw_deck_zone = "e6cfee",
        discard_deck_zone = "6bb3b6",
        first_player_zone = "e9a44c",
        banner_bag = "b92a4c",
        councilor = "1be491",
        agents = {
            "5068c8",
            "67b476"
        },
        dreadnoughts = {
            "5469fb",
            "71a414"
        },
        pv_board = "99a860",
        pv_board_zone = "b25c3c",
        troup_zone = "ffbd81",
        troup_bowl = "6af67a",
        troups = {
            "ef6da2",
            "4d0dbf",
            "7c5b7b",
            "fbf8d2",
            "d01e0b",
            "79cbf1",
            "96d089",
            "b5d32e",
            "9b55e4"
        },
        spice_counter = "78fb8a",
        solari_counter = "c5c4ef",
        water_counter = "f217d0",
        pass_turn_anchor = "65876d",
        agent_turn_text = "f91adf",
        agent_and_reveal_zone = "ae1ef8",
        tech_board = "d69aec",
        tech_board_text = "dd3a7e",
        tech_board_zone = "3d705e",
        trash = "7d1e07",
        hand_trigger = "050f39",
        ["VP 4 Players"] = "4e8873",
        ix_atomics = "7e10a9"
        },
        Blue = {
        board = "6957f2",
        character_zone = "681774",
        draw_deck = "0c5e03",
        draw_deck_zone = "907f66",
        discard_deck_zone = "26bf8b",
        first_player_zone = "1fc559",
        banner_bag = "8627e0",
        councilor = "f5b14a",
        agents = {
            "64d013",
            "106d8b"
        },
        dreadnoughts = {
            "82789e",
            "60f208"
        },
        pv_board = "121bb6",
        pv_board_zone = "376f34",
        troup_zone = "2a520c",
        troup_bowl = "b71dd9",
        troups = {
            "bc6e74",
            "5fba3c",
            "f2c21f",
            "2a5276",
            "f60d9c",
            "949f2d",
            "0e57c9",
            "694553",
            "f65e5d"
        },
        spice_counter = "9cc286",
        solari_counter = "fa5236",
        water_counter = "0afaeb",
        pass_turn_anchor = "643f32",
        agent_turn_text = "208519",
        agent_and_reveal_zone = "f20a74",
        tech_board = "b24cc5",
        tech_board_text = "f51654",
        tech_board_zone = "2d3346",
        trash = "52a539",
        hand_trigger = "e50f77",
        ["VP 4 Players"] = "311255",
        ix_atomics = "700023"
        },
        Red = {
        board = "daf2a3",
        character_zone = "66cdbb",
        draw_deck = "014c6a",
        draw_deck_zone = "4f08fc",
        discard_deck_zone = "e07493",
        first_player_zone = "346e0d",
        banner_bag = "61453d",
        councilor = "f19a48",
        agents = {
            "7751c8",
            "afa978"
        },
        dreadnoughts = {
            "1a3c82",
            "a8f306"
        },
        pv_board = "e0ed4b",
        pv_board_zone = "5b9a53",
        troup_zone = "ab8fdf",
        troup_bowl = "8ea4af",
        troups = {
            "fd5673",
            "81763a",
            "6c2b85",
            "8b2acc",
            "8bb1e6",
            "26904f",
            "d1787e",
            "af7cd0",
            "1bbf1c"
        },
        spice_counter = "3074d4",
        solari_counter = "576ccd",
        water_counter = "692c4d",
        pass_turn_anchor = "0e9fa2",
        agent_turn_text = "ca435b",
        agent_and_reveal_zone = "cd9716",
        tech_board = "8b1f92",
        tech_board_text = "e940a6",
        tech_board_zone = "9555b8",
        trash = "ea3fe1",
        hand_trigger = "8a9816",
        ["VP 4 Players"] = "a6c2e0",
        ix_atomics = "d5ff47"
        }
    },
    immortality_row = {
        _deck = "36340e",
        deck = "dcad54",
        deck_zone = "14b2ca",
        pay1_zone = "e5ba35",
        pay1_anchor = "439df9",
        pay2_zone = "1e5a32",
        pay2_anchor = "363f98",
        reclaim_forces_deck = "3c772c"
    },
    imperium_row = {
        ["Foldspace Deck"] = "014161",
        foldspace_deck_zone = "6b62e0",
        ["Arrakis Liaison Deck"] = "7d34c9",
        arrakis_liaison_deck_zone = "cbcd9a",
        ["The Spice Must Flow Deck"] = "8de6d5",
        the_spice_must_flow_deck_zone = "c087d2",
        the_spice_must_flow_deck_anchor = "6a1097",
        Deck = "99d41d",
        deck_zone = "8bd982",
        buy1_anchor = "38ffc0",
        buy1_zone = "3de1d0",
        buy2_anchor = "21b287",
        buy2_zone = "356e2c",
        buy3_anchor = "0a5f50",
        buy3_zone = "7edbb3",
        buy4_anchor = "ded672",
        buy4_zone = "641974",
        buy5_anchor = "ad2a82",
        buy5_zone = "c6dbed"
    },
    intrigue = {
        intrigue_deck = "77d25d",
        intrigue_deck_zone = "a377d8",
        intrigue_deck_anchor = "976c3a",
        intrigue_discard_back_card = "90f762"
    },
    base = {
        board = "2da390",
        board_zone = "c68e45",
        ["Board Base / Ix CHOAM Overlay"] = "a139cd",
        spaces = {
            conspire_zone = "cd9386",
            wealth_zone = "b2c461",
            heighliner_zone = "8b0515",
            foldspace_zone = "9a9eb5",
            selective_breeding_snooper_zone = "7dc6e5",
            secrets_zone = "1f7c08",
            hardy_warriors_zone = "a2fd8e",
            stillsuits_zone = "556f43",
            smuggling_zone = "6cc2f8",
            swordmaster_zone = "6932df",
            high_council_zone = "8a6315",
            mentat_zone = "30cff9",
            interstellar_shipping_zone = "3e7409",
            high_council_token_zone = "e51f6e",
            arrakeen_zone = "17b646",
            carthag_zone = "b1c938",
            research_station_zone = "af11aa",
            siech_tabr_zone = "5bc970",
            imperial_bassin_zone = "2c77c1",
            hagga_bassin_zone = "622708",
            the_great_flat_zone = "69f925",
            secure_contract_zone = "db4022",
            sell_melange_zone = "7539a3"
        },
        other_spaces = {
            arrakeen_banner_zone = "f1f53d",
            carthag_banner_zone = "9fc2e1",
            imperial_bassin_banner_zone = "3fe117",
            ["Spice Bonus - Imperial Bassin"] = "3cdb2d",
            ["Spice Bonus - Hagga Bassin"] = "394db2",
            ["Spice Bonus - The Great Flat"] = "116807"
        },
        ["First Player Picker anchor"] = "d84873",
        ["First Player Marker"] = "1f5576",
        ["First Conflict anchor"] = "cb0478",
        ["Councellor Influence Bonus Bag"] = "074f6d",
        mentat = "c2a908",
        mentat_zone = "565d09",
        ["Makers & Recall anchor"] = "120026",
        ["Makers & Recall"] = "fb41e2",
        ["Setup UI anchor"] = "4a3e76",
        factions = {
            Emperor = {
                level6_zone = "816e58",
                level4_zone = "2c3c38",
                level2_zone = "aae631",
                alliance = "13e990",
                ["2 influences Bag"] = "6a4186",
                Green = "d7c9ba",
                Yellow = "489871",
                Blue = "426a23",
                Red = "acfcef"
            },
            ["Spacing Guild"] = {
                level6_zone = "410b39",
                level4_zone = "8d2035",
                level2_zone = "768e1e",
                alliance = "ad1aae",
                ["2 influences Bag"] = "400d45",
                Green = "89da7d",
                Yellow = "9d0075",
                Blue = "4069d8",
                Red = "be464e"
            },
            ["Bene Gesserit"] = {
                level6_zone = "799810",
                level4_zone = "53e26c",
                level2_zone = "bd1e3b",
                alliance = "33452e",
                ["2 influences Bag"] = "e763f6",
                Green = "2dc980",
                Yellow = "a3729e",
                Blue = "2a88a6",
                Red = "713eae"
            },
            Fremen = {
                level6_zone = "ec30be",
                level4_zone = "ae150a",
                level2_zone = "4a1ce8",
                alliance = "4c2bcc",
                ["2 influences Bag"] = "8bcfe7",
                Green = "d390dc",
                Yellow = "77d7c8",
                Blue = "0e6e41",
                Red = "088f51"
            }
        },
        players = {
            Green = {
                score_token = "76039f",
                pre_deployed_troups = {
                "2b1cf8",
                "8e22cc",
                "866a9c"
                },
                ix_cargo = "34281d"
            },
            Yellow = {
                score_token = "20bbd1",
                pre_deployed_troups = {
                "fd7fc7",
                "ef9008",
                "734b6e"
                },
                ix_cargo = "8fa76f"
            },
            Blue = {
                score_token = "1b1e76",
                pre_deployed_troups = {
                "c64616",
                "46c1c6",
                "49afee"
                },
                ix_cargo = "68e424"
            },
            Red = {
                score_token = "4feaca",
                pre_deployed_troups = {
                "1fb4ed",
                "0fa955",
                "465c38"
                },
                ix_cargo = "e9096d"
            }
        },
        combat = {
            level3_conflicts = "f9ea6b",
            level2_conflicts = "7c9ceb",
            level1_conflicts = "616984",
            level3_conflicts_zone = "07e239",
            combat_detection_zone = "722609",
            vp_combat_reward_zone = "740624",
            small_square_zone = "43f00f",
            combat_center_zone = "6d632e",
            combat_tokens_zone = "1d4424",
            Green = "a1a9a7",
            Yellow = "c2dd31",
            Blue = "f22e20",
            Red = "2d1d17"
        }
    },
    ix = {
        ["Board Planet Ix"] = "d75455",
        spaces = {
        ix_dreadnough_zone = "83ea90"
        }
    },
    immortality = {
        specimen_zone = "f5de09",
        first_limit_zone = "042b49",
        first_limit_after_zone = "da08cd",
        second_limit_zone = "60a0fd",
        intrigue_bonus_zone = "1054b7",
        vp_spice_bonus_zone = "5e4d40",
        another_intrigue_bonus_zone = "5d6083",
        vp_bonus_zone = "a1a4e8",
        ["Bene Tleilax Board"] = "d5c2db",
        ["Tleilaxu bonus spice"] = "46cd6b",
        cells = {
            "ab9e8d",
            "d2b9be",
            "90e82d",
            "659227",
            "95bb64",
            "1696ae",
            "1f11e0",
            "79f487",
            "6518bf",
            "778685",
            "d4fb57",
            "52bcf4",
            "f9ddaa",
            "e91e6b",
            "b60372",
            "f8c1b0",
            "8a3807",
            "78a5cf",
            "2a7803",
            "6c0d3e",
            "459e80"
        },
        players = {
        Green = {
            ["BT track"] = "63d39f",
            ["Research track"] = "658b17"
        },
        Yellow = {
            ["BT track"] = "d20bcf",
            ["Research track"] = "8988cf"
        },
        Blue = {
            ["BT track"] = "96607f",
            ["Research track"] = "292658"
        },
        Red = {
            ["BT track"] = "2bfc39",
            ["Research track"] = "39e0f3"
        }
        }
    },
    black_market = {
        pay1_zone = "323acb",
        pay2_zone = "e96c10",
        pay3_zone = "93de6d",
        board = "ab7ac5"
    },
    deprecated = {
        ["Flex Table Control"] = "bd69bd",
        Custom_Assetbundle_0 = "4ee1f2",
        Custom_Assetbundle_1 = "afc863",
        Custom_Assetbundle_2 = "c8edca",
        Custom_Assetbundle_3 = "393bf7",
        Custom_Assetbundle_4 = "12c65e",
        Custom_Assetbundle_5 = "f938a2",
        Custom_Assetbundle_6 = "9f95fd",
        Custom_Assetbundle_7 = "35b95f",
        Custom_Assetbundle_8 = "5af8f2",
        Die_6_1 = "2250ef",
        Die_6_2 = "a47416",
        unused_board = "e1e919"
    }
}

_ = core.registerLoadablePart(function(_)
    constants.players = {}
    -- Do not confuse alive players with active players. Without restoring a save,
    -- all players stay alive.
    constants.alivePlayers = {}

    for color, unresolvedPlayer in pairs(constants.unresolvedPlayers) do
        -- Too many objects could be legitimately missing in the middle of a
        -- game, event for alive players, so we simply disable the unresolved
        -- GUID reporting.
        local player = core.resolveGUIDs(false, unresolvedPlayer)
        constants.players[color] = player
        -- Not having a swordmaster anymore is a sure sign that a player has
        -- been shutdown.
        local alive = getObjectFromGUID(unresolvedPlayer.swordmaster) ~= nil
        if alive then
            constants.alivePlayers[color] = player
        end
    end
    constants.unresolvedPlayers = nil

    -- Extrapolate two other positions (for the swordmaster and the mentat)
    -- from the positions of the two existing agents.
    for _, player in pairs(constants.players) do
        assert(#player.agent_positions == 2)
        local p1 = player.agent_positions[1]
        local p2 = player.agent_positions[2]
        player.agent_positions[3] = p2 + (p2 - p1)
        player.agent_positions[4] = p2 + (p2 - p1) * 2
    end

    constants.structure = core.resolveGUIDs(false, constants.unresolvedStructure)
    constants.unresolvedStructure = nil

    -- TODO Use the anchor instead of the token itself.
    -- "Makers & Recall anchor": "120026",
    -- "Makers & Recall": "fb41e2",
    local p = constants.structure.main.maker_initial_position
    constants.marker_positions = {
        round_start = p + Vector(0, 0, -0.64 * 0),
        player_turns = p + Vector(0, 0, -0.64 * 1),
        combat = p + Vector(0, 0, -0.64 * 2),
        makers = p + Vector(0, 0, -0.64 * 3),
        recall = p + Vector(0, 0, -0.64 * 4)
    }
end)

return constants
