_ = require("Core").registerLoadablePart(function()
    self.createButton({
        click_function = 'doNothing',
        function_owner = self,
        label = 'First Player',
        position = {0, 0.5, 0},
        rotation = {0, 180, 0},
        width = 1600,
        height = 500,
        font_size = 250
    })
    self.setInvisibleTo({ "White", "Blue", "Red", "Yellow", "Green", "Grey", "Black" })
    self.interactable = false
end)

function doNothing() end
